name: Install SnowSQL

on:
  push:
    branches:
      - main

jobs:
  install-snowSQL:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version if needed

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl  # Ensure curl is installed

      - name: Download SnowSQL
        run: |
          # Download the latest SnowSQL package
          curl -o snowsql-linux_x86_64_latest.tar.gz -L "https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2.20/linux_x86_64/snowflake_snowsql_linux_x86_64_1.2.20.tar.gz"
          
      - name: Extract SnowSQL
        run: |
          tar -xzf snowsql-linux_x86_64_latest.tar.gz
          cd snowflake_snowsql-linux_x86_64_1.2.20  # Change to the extracted directory
          sudo ./install.sh  # Run the installation script

      - name: Verify SnowSQL installation
        run: |
          snowsql --version  # Check the installed version
