name: Deploy data pipeline to prod

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Download SnowSQL Installer
        run: |
          wget https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.24-linux_x86_64.bash -O snowsql_install.bash
          # Verify file downloaded
          ls -lh snowsql_install.bash

      - name: Install SnowSQL
        run: |
          chmod +x snowsql_install.bash
          # Run the installer and capture output
          ./snowsql_install.bash -b ~/bin || { echo "SnowSQL installation failed"; exit 1; }

          # Add SnowSQL to PATH
          echo "export PATH=~/bin:\$PATH" >> $GITHUB_ENV

      - name: Verify SnowSQL installation
        run: |
          # Ensure SnowSQL is added to PATH for this session
          export PATH=~/bin:$PATH
          # Check the SnowSQL version and capture output
          ~/bin/snowsql -v || { echo "SnowSQL not found"; exit 1; }
