name: CI

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
          SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash

      - name: Check SnowSQL Version
        run: |
          ~/bin/snowsql --version

      - name: Get the list of modified SQL scripts
        id: modified_files
        run: |
          # Get the list of modified files in the latest commit
          git diff --name-only HEAD~1 HEAD > modified_files.txt
          # Filter only SQL files
          grep '\.sql$' modified_files.txt > sql_files.txt
          cat sql_files.txt

      - name: Run SnowSQL for each modified SQL file
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWSQL_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWSQL_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          # Loop through each modified SQL file and execute it
          for file in $(cat sql_files.txt); do
            echo "Running $file"
            ~/bin/snowsql -q "
              USE DATABASE CI_CD_DEMO;
              USE SCHEMA DEMO_SCHEMA;
              EXECUTE IMMEDIATE FROM @$file;"
          done
