name: CI

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetch at least 2 commits to avoid shallow clone issues

      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
          SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash

      - name: Check SnowSQL Version
        run: |
          ~/bin/snowsql --version

      - name: Get the list of modified SQL scripts
        id: modified_files
        run: |
          # Ensure we handle cases with no previous commit gracefully
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            # Get the list of modified files between the last two commits
            git diff --name-only HEAD~1 HEAD > modified_files.txt
          else
            # If no previous commit, get all committed files in the current commit
            git ls-tree --name-only --full-tree HEAD > modified_files.txt
          fi
          
          # Filter only SQL files, and ensure the script continues if no SQL files are found
          grep '\.sql$' modified_files.txt > sql_files.txt || true
          
          # Show the modified SQL files (if any)
          if [ -s sql_files.txt ]; then
            echo "Modified SQL files:"
            cat sql_files.txt
          else
            echo "No SQL files modified."
          fi

      - name: Run SnowSQL for each modified SQL file
        if: steps.modified_files.outputs.modified_files != ''
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWSQL_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWSQL_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          ~/bin/snowsql -q "ALTER GIT REPOSITORY CI_CD_DEMO.DEMO_SCHEMA.snowflake_extensions FETCH;"
          
          # If any SQL files are found, execute them with SnowSQL
          for file in $(cat sql_files.txt); do
            echo "Running $file"
            ~/bin/snowsql -q "
              USE DATABASE CI_CD_DEMO;
              USE SCHEMA DEMO_SCHEMA;
              EXECUTE IMMEDIATE FROM @snowflake_extensions/branches/main/$file;"
          done
