name: Deploy data pipeline to prod

# Controls when the action will run.
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Download SnowSQL Installer
        run: |
          # Download SnowSQL installer with logging
          wget https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.24-linux_x86_64.bash \
          -O snowsql_install.bash

          # Verify file was downloaded
          ls -lh snowsql_install.bash

      - name: Install SnowSQL with Logging
        run: |
          # Give execution permissions
          chmod +x snowsql_install.bash

          # Attempt installation with debug logging
          sudo bash snowsql_install.bash -b ~/bin | tee snowsql_install.log

          # Check the log file for errors
          cat snowsql_install.log

      - name: Verify SnowSQL Installation
        run: |
          # Verify if SnowSQL was installed successfully
          export PATH=~/bin:$PATH
          snowsql -v

      - name: Deploy data pipeline
        run: |
          snow sql -q "ALTER GIT REPOSITORY CI_CD_DEMO.DEMO_SCHEMA.snowflake_extensions FETCH" --temporary-connection --account ve05214.ap-southeast-1 --user Meghana --password Meghanasri@5 --role ACCOUNTADMIN --warehouse COMPUTE_WH
