name: Deploy data pipeline to prod

# Controls when the action will run.
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Download SnowSQL Installer
        run: |
          wget https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.24-linux_x86_64.bash \
          -O snowsql_install.bash

          # Verify file downloaded
          ls -lh snowsql_install.bash

      - name: Install SnowSQL
        run: |
          chmod +x snowsql_install.bash
          sudo ./snowsql_install.bash -b ~/bin

          # Add SnowSQL to PATH
          echo "export PATH=~/bin:\$PATH" >> ~/.bashrc
          source ~/.bashrc

          # Verify SnowSQL installation
          ~/bin/snowsql -v

      - name: Verify SnowSQL Installation
        run: |
          # Ensure SnowSQL is added to PATH for this session
          export PATH=~/bin:$PATH

          # Check the SnowSQL version
          snowsql -v

      - name: Deploy data pipeline
        run: |
          snow sql -q "ALTER GIT REPOSITORY CI_CD_DEMO.DEMO_SCHEMA.snowflake_extensions FETCH" --temporary-connection --account ve05214.ap-southeast-1 --user Meghana --password Meghanasri@5 --role ACCOUNTADMIN --warehouse COMPUTE_WH
