name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on any branch or tag commit
  push:
    branches:
      - "*"
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is available to access previous commits

      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
          SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash

      - name: Check SnowSQL Version
        run: |
          ~/bin/snowsql --version

      # Run a SnowSQL Command using environment variables for Snowflake connection details
      - name: Run SnowSQL Command
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWSQL_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWSQL_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          # Define a function to execute the SnowSQL command
          execute_snow_sql() {
            ~/bin/snowsql -q "$1"
            return $?  # Return the exit status of the SnowSQL command
          }

          # Command to run
          command="SELECT CURRENT_VERSION();"
          
          # Try to execute the command
          execute_snow_sql "$command" || {
            # If the command fails, execute the fallback
            echo "Initial command failed, executing the last committed version..."

            # Checkout the last committed version of the SQL script
            git checkout HEAD~1 --force

            # Execute the last committed version of the script
            execute_snow_sql "USE DATABASE CI_CD_DEMO; USE SCHEMA DEMO_SCHEMA; EXECUTE IMMEDIATE FROM @snowflake_extensions/branches/main/SQL_SCRIPT.SQL;"
          }

          # Next command to run
          command="ALTER GIT REPOSITORY CI_CD_DEMO.DEMO_SCHEMA.snowflake_extensions FETCH;"
          
          # Try to execute the command
          execute_snow_sql "$command" || {
            # If the command fails, execute the fallback
            echo "ALTER command failed, executing the last committed version..."

            # Checkout the last committed version of the SQL script
            git checkout HEAD~1 --force

            # Execute the last committed version of the script
            execute_snow_sql "USE DATABASE CI_CD_DEMO; USE SCHEMA DEMO_SCHEMA; EXECUTE IMMEDIATE FROM @snowflake_extensions/branches/main/SQL_SCRIPT.SQL;"
          }

          # Final command to run
          command="USE DATABASE CI_CD_DEMO; USE SCHEMA DEMO_SCHEMA; EXECUTE IMMEDIATE FROM @snowflake_extensions/branches/main/SQL_SCRIPT.SQL;"
          
          # Try to execute the command
          execute_snow_sql "$command" || {
            # If the command fails, execute the fallback
            echo "Final command failed, executing the last committed version..."

            # Checkout the last committed version of the SQL script
            git checkout HEAD~1 --force

            # Execute the last committed version of the script
            execute_snow_sql "USE DATABASE CI_CD_DEMO; USE SCHEMA DEMO_SCHEMA; EXECUTE IMMEDIATE FROM @snowflake_extensions/branches/main/SQL_SCRIPT.SQL;"
          }
