name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on any branch or tag commit
  push:
    branches:
      - "*"
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
          SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash

      - name: Check SnowSQL Version
        run: |
          ~/bin/snowsql --version

      # Get list of modified SQL files from the latest commit
      - name: Get Modified SQL Files
        id: get_modified_files
        run: |
          echo "Getting modified SQL files..."
          git fetch origin main  # Fetch latest from remote

          # Get the list of modified files in the latest commit
          modified_files=$(git diff --name-only HEAD~1 HEAD | grep '\.sql$')

          # Check if any modified files were found
          if [ -z "$modified_files" ]; then
            echo "No modified SQL files found."
            echo "::set-output name=modified_files::"  # Set output to empty if no files found
          else
            echo "$modified_files"
            echo "$modified_files" > modified_files.txt
            echo "::set-output name=modified_files::$modified_files"  # Set output with the list of files
          fi

      # Run SnowSQL commands for each modified SQL file
      - name: Execute Modified SQL Files
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWSQL_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWSQL_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          ~/bin/snowsql -q "SELECT CURRENT_VERSION();"
          ~/bin/snowsql -q "ALTER GIT REPOSITORY CI_CD_DEMO.DEMO_SCHEMA.snowflake_extensions FETCH;"

          echo "Executing modified SQL files..."
          if [[ -f modified_files.txt ]]; then
            while IFS= read -r sql_file; do
              echo "Executing $sql_file..."
              ~/bin/snowsql -q "USE DATABASE CI_CD_DEMO;
                                USE SCHEMA DEMO_SCHEMA;
                                EXECUTE IMMEDIATE FROM @snowflake_extensions/branches/main/$sql_file;"
            done < modified_files.txt
          else
            echo "No SQL files to execute."
          fi
