name: CI with Fallback to Previous Version

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
          SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash

      - name: Check SnowSQL Version
        run: |
          ~/bin/snowsql --version

      - name: Execute SQL with Try-Catch Logic
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWSQL_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWSQL_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          ~/bin/snowsql -q "ALTER GIT REPOSITORY CI_CD_DEMO.DEMO_SCHEMA.snowflake_extensions FETCH;"

          # Define function to simulate try-catch behavior
          function try_catch() {
            "$@"
            status=$?
            return $status
          }

          # Get the latest SQL script file names dynamically
          sql_files=$(git ls-tree -r HEAD --name-only | grep '\.SQL$')

          # Loop through each SQL file and execute
          for latest_file in $sql_files; do
            echo "Trying to execute SQL script: $latest_file..."
            if try_catch ~/bin/snowsql -q "USE DATABASE CI_CD_DEMO; USE SCHEMA DEMO_SCHEMA; EXECUTE IMMEDIATE FROM @snowflake_extensions/branches/main/$latest_file"; then
              echo "$latest_file executed successfully."
            else
              echo "Failed to execute $latest_file. Moving to fallback (previous version)..."

              # Catch block: run the previous version of the SQL script
              previous_file="branches/main/$(git rev-parse HEAD~1):$latest_file"
              echo "Attempting to run previous version: $previous_file"

              if try_catch ~/bin/snowsql -q "USE DATABASE CI_CD_DEMO; USE SCHEMA DEMO_SCHEMA; EXECUTE IMMEDIATE FROM @snowflake_extensions/${previous_file};"; then
                echo "Previous version of $latest_file executed successfully."
              else
                echo "Failed to execute both the latest and previous versions of $latest_file."
                exit 1  # Exit with failure if both attempts fail
              fi
            fi
          done
