name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on any branch or tag commit
  push:
    branches:
      - "*"
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
          SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash

      - name: Check SnowSQL Version
        run: |
          ~/bin/snowsql --version

      # List all files in the repository
      - name: List All Files
        id: list_files
        run: |
          echo "Listing all files in the repository:"
          git ls-files > files_list.txt
          cat files_list.txt

      # Filter for .sql files and execute them
      - name: Execute SQL Files
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWSQL_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWSQL_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          ~/bin/snowsql -q "SELECT CURRENT_VERSION();"
          ~/bin/snowsql -q "ALTER GIT REPOSITORY CI_CD_DEMO.DEMO_SCHEMA.snowflake_extensions FETCH;"

          echo "Executing SQL files..."
          # Read the list of files and filter for .sql files
          while IFS= read -r sql_file; do
            if [[ "$sql_file" == *.SQL ]]; then
              echo "Executing $sql_file..."
              ~/bin/snowsql -q "USE DATABASE CI_CD_DEMO;
                                USE SCHEMA DEMO_SCHEMA;
                                EXECUTE IMMEDIATE FROM @snowflake_extensions/branches/main/$sql_file;"
            fi
          done < files_list.txt
