name: CI

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full commit history

      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
          SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash

      - name: Check SnowSQL Version
        run: |
          ~/bin/snowsql --version

      - name: Get the list of modified SQL scripts
        id: modified_files
        run: |
          # Fetch modified files
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            git diff --name-only HEAD~1 HEAD > modified_files.txt
          else
            git ls-tree --name-only --full-tree HEAD > modified_files.txt
          fi
          
          # Show modified files and filter for SQL files
          echo "Modified files:"
          cat modified_files.txt
          grep -i '\.sql$' modified_files.txt > sql_files.txt || true

          if [ -s sql_files.txt ]; then
            echo "Modified SQL files:"
            cat sql_files.txt
          else
            echo "No SQL files modified."
          fi

      - name: Run SnowSQL Command
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWSQL_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWSQL_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          set -e  # Exit on error

          # Fetch latest from Snowflake repository
          ~/bin/snowsql -q "ALTER GIT REPOSITORY CI_CD_DEMO.DEMO_SCHEMA.snowflake_extensions FETCH;"

          if [ -s sql_files.txt ]; then
            while IFS= read -r file; do
              echo "Running SQL file: $file"

              # Run the current SQL file
              if ! ~/bin/snowsql -q "
                USE DATABASE CI_CD_DEMO;
                USE SCHEMA DEMO_SCHEMA;
                EXECUTE IMMEDIATE FROM @snowflake_extensions/branches/main/$file;"; then
                
                # If the current script fails, run the previous version
                echo "Failed to run $file. Attempting to run previous version of the script."
                
                previous_file="branches/main/$(git rev-parse HEAD~1):$file"
                if ~/bin/snowsql -q "
                  USE DATABASE CI_CD_DEMO;
                  USE SCHEMA DEMO_SCHEMA;
                  EXECUTE IMMEDIATE FROM @snowflake_extensions/${previous_file};"; then
                  echo "Successfully ran previous version of $file."
                else
                  echo "Failed to run previous version of $file. Exiting."
                  exit 1
                fi
              fi
            done < sql_files.txt
          else
            echo "No SQL files to execute."
          fi
