name: CI with Fallback to Previous Version

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Fetch full git history to access previous commits
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is available

      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
          SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash

      - name: Check SnowSQL Version
        run: |
          ~/bin/snowsql --version

      - name: Execute SQL with Try-Catch Logic
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWSQL_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWSQL_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          ~/bin/snowsql -q "ALTER GIT REPOSITORY CI_CD_DEMO.DEMO_SCHEMA.snowflake_extensions FETCH;"

          # Get the latest SQL script file names dynamically
          sql_files=$(git ls-tree -r HEAD --name-only | grep '\.SQL$')

          # Log the SQL files identified
          echo "SQL files found in the latest commit:"
          echo "$sql_files"

          # Loop through each SQL file and execute
          for latest_file in $sql_files; do
            echo "Trying to execute SQL script: $latest_file..."

            # Execute the SQL script and capture the output
            output=$(~/bin/snowsql -q "USE DATABASE CI_CD_DEMO; USE SCHEMA DEMO_SCHEMA; EXECUTE IMMEDIATE FROM @snowflake_extensions/branches/main/$latest_file" 2>&1)
            status=$?

            # Output the status of the command
            echo "Execution status for $latest_file: $status"
            echo "Output: $output"

            # Check for error messages in the output (in addition to status code)
            if [[ "$output" == *"Uncaught exception"* ]] || [[ "$output" == *"SQL compilation error"* ]]; then
              echo "Detected error in output: $output"
              echo "Moving to fallback (previous version)..."

              # Checkout the previous commit
              git checkout HEAD~1  # Switch to the previous commit

              # Log the files in the previous commit to ensure the SQL script is available
              echo "Checking files in previous commit:"
              git ls-tree -r HEAD --name-only | grep '\.SQL$'

              # Check if the file exists in the previous commit before executing
              if git ls-tree -r HEAD --name-only | grep -q "$latest_file"; then
                echo "Found $latest_file in previous commit. Executing fallback..."

                # Execute the previous version
                output_fallback=$(~/bin/snowsql -q "USE DATABASE CI_CD_DEMO; USE SCHEMA DEMO_SCHEMA; EXECUTE IMMEDIATE FROM @snowflake_extensions/branches/main/$latest_file;" 2>&1)
                status_fallback=$?

                # Output the status of the fallback command
                echo "Execution status for previous version of $latest_file: $status_fallback"
                echo "Fallback Output: $output_fallback"

                # Check if the fallback execution was successful
                if [ $status_fallback -ne 0 ] || [[ "$output_fallback" == *"Uncaught exception"* ]] || [[ "$output_fallback" == *"SQL compilation error"* ]]; then
                  echo "Failed to execute both the latest and previous versions of $latest_file. Error: $output_fallback"
                  exit 1  # Exit with failure if both attempts fail
                else
                  echo "Previous version of $latest_file executed successfully."
                fi
              else
                echo "$latest_file does not exist in the previous commit. Skipping fallback."
              fi

              # Switch back to the main branch after fallback
              git checkout -
            else
              echo "$latest_file executed successfully."
            fi
          done
